import type { AgentState } from "../types/agent";

const now = new Date();

export const demoState: AgentState = {
  positions: [
    {
      id: "pos-1",
      symbol: "ETH-PERP",
      venue: "dYdX",
      chain: "Ethereum",
      side: "LONG",
      leverage: 7.2,
      notional: 18400,
      margin: 2555,
      buffer: 14.2,
      funding: -0.012,
      pnl: 340,
      bufferTarget: 15,
      volatility: 0.42,
    },
    {
      id: "pos-2",
      symbol: "SOL-PERP",
      venue: "GMX",
      chain: "Arbitrum",
      side: "LONG",
      leverage: 9.1,
      notional: 11200,
      margin: 1230,
      buffer: 8.4,
      funding: 0.008,
      pnl: -120,
      bufferTarget: 12,
      volatility: 0.68,
    },
    {
      id: "pos-3",
      symbol: "BTC-PERP",
      venue: "Hyperliquid",
      chain: "Hyperliquid L1",
      side: "SHORT",
      leverage: 4.5,
      notional: 32000,
      margin: 7111,
      buffer: 22.1,
      funding: 0.003,
      pnl: 880,
      bufferTarget: 18,
      volatility: 0.31,
    },
    {
      id: "pos-4",
      symbol: "ARB-PERP",
      venue: "Vertex",
      chain: "Arbitrum",
      side: "LONG",
      leverage: 6,
      notional: 5400,
      margin: 900,
      buffer: 11.7,
      funding: -0.005,
      pnl: 60,
      bufferTarget: 12,
      volatility: 0.55,
    },
  ],
  policy: {
    profile: "Balanced",
    maxLeverage: 8,
    minBuffer: 10,
    maxEmergencySpend: 500,
    dailySpendCap: 1500,
    spentToday: 0,
    allowedVenues: ["Hyperliquid", "dYdX", "GMX", "Vertex"],
    allowedChains: ["Ethereum", "Arbitrum", "Hyperliquid L1"],
    autoHedge: false,
    paused: false,
    contractAddress: "0x0000000000000000000000000000000000000000",
  },
  autopilot: false,
  shockActive: false,
  metrics: {
    liquidationsPrevented: 0,
    actionsBlocked: 0,
    usdcRouted: 0,
    sessionReceiptsCount: 0,
  },
  wallet: {
    connected: false,
    address: "",
    walletId: null,
    usdcBalance: 0,
    balanceUpdatedAt: null,
    balanceStatus: "unconfigured",
    balanceError: "Backend is offline. Demo state is local only.",
    agentErc8004Id: "demo",
  },
  chain: {
    chainId: 5042002,
    name: "Arc Testnet",
    rpcUrl: "https://rpc.testnet.arc.network",
    explorerUrl: "https://testnet.arcscan.app",
    gasToken: "USDC",
    nativeDecimals: 18,
    policyAmountDecimals: 6,
  },
  runtime: {
    startedAt: now.toISOString(),
    lastCycleAt: null,
    lastError: null,
    cycleInProgress: false,
    autopilotWritesEnabled: false,
    autopilotTickCount: 0,
    lastPolicySyncTxHash: null,
    lastPolicySyncAt: null,
  },
  adapters: ["Hyperliquid", "dYdX", "GMX", "Vertex"].map((name) => ({
    id: name.toLowerCase().replace(/[^a-z0-9]/g, ""),
    name,
    status: "simulated" as const,
    disclosure: "Venue execution adapter is simulated; Arc policy receipt is real only when txHash is present.",
    lastActionAt: null,
  })),
  signing: {
    mode: "unconfigured",
    primary: "none",
    fallbackActive: false,
    contractAddress: "0x0000000000000000000000000000000000000000",
    authorizedAgentAddress: null,
    circleAgentAddress: null,
    fallbackAgentAddress: null,
    disclosure: "Demo mode is local. No transaction is broadcast.",
    lastTxHash: null,
    lastCircleTransactionId: null,
  },
  integrations: {
    circleWallet: {
      status: "unconfigured",
      configured: false,
      walletId: null,
      address: null,
      walletSetId: null,
      blockchain: "ARC-TESTNET",
      accountType: null,
      walletState: null,
      artifactPath: null,
      contractAgentAddress: null,
      matchesPolicyAgent: null,
      message: "Backend unavailable. Circle wallet status is not live.",
      checkedAt: null,
    },
    balance: {
      status: "unconfigured",
      usdcBalance: 0,
      updatedAt: null,
      error: "Backend unavailable.",
      ttlMs: 0,
    },
    identity: {
      status: "unconfigured",
      agentId: null,
      registryAddress: "0x0000000000000000000000000000000000000000",
      agentAddress: null,
      metadataUri: null,
      metadataHash: null,
      txHash: null,
      circleTransactionId: null,
      explorerUrl: null,
      signerMode: "none",
      blocker: "Backend unavailable.",
      updatedAt: null,
    },
    telegram: {
      status: "unconfigured",
      configured: false,
      disclosure: "Telegram is optional and unavailable in local demo mode.",
    },
  },
  newestReceiptId: null,
  receipts: [
    {
      id: "seed-receipt-1",
      receiptId: 0,
      time: new Date(now.getTime() - 12 * 60_000).toISOString(),
      action: "add-collateral",
      title: "Seeded 320 USDC collateral route",
      venue: "dYdX",
      pair: "ETH-PERP",
      amount: 320,
      bufferBefore: 9.6,
      bufferAfter: 13.4,
      status: "simulated",
      primitive: "Gateway + CCTP",
      reason: "Seed demo receipt. No Arc transaction was broadcast for this row.",
      txId: "DEMO-SEED-1",
      seeded: true,
      executionDisclosure: "Seeded demo receipt with no txHash.",
    },
    {
      id: "seed-receipt-2",
      receiptId: 0,
      time: new Date(now.getTime() - 28 * 60_000).toISOString(),
      action: "block",
      title: "Seeded blocked 12.4x leverage request",
      venue: "GMX",
      pair: "SOL-PERP",
      bufferBefore: 8.2,
      bufferAfter: 8.2,
      status: "blocked",
      primitive: "Policy Contract",
      reason: "Seed demo receipt. Requested leverage exceeded the Balanced policy cap.",
      txId: "DEMO-SEED-2",
      seeded: true,
      executionDisclosure: "Seeded demo receipt with no txHash.",
    },
  ],
  liquidationsPrevented: 0,
  actionsBlocked: 0,
  usdcRouted: 0,
  sessionReceiptsCount: 0,
  walletConnected: false,
  walletAddress: "",
  usdcBalance: 0,
  agentErc8004Id: "demo",
  lastCycleAt: null,
};
